import type { Metadata } from "next";
import { DM_Sans, Karla } from "next/font/google";

import "./globals.css";

import { GsapProvider } from "@/lib/gsap/providers/GsapProvider";
import LenisProvider from "@/lib/gsap/providers/LenisProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${dmSans.variable} ${karla.variable}`}
    >
      <body suppressHydrationWarning>
        <LenisProvider>
          <Navbar />
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
